name: Mark issue as awaiting response on comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  mark_awaiting:
    runs-on: ubuntu-latest
    steps:
      - name: Add awaiting-response label and comment
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;

            // Skip if this is a comment on a PR, not an issue
            if (!issue || issue.pull_request) return;

            const issue_number = issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // 1. Add the "awaiting-response" label
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['awaiting-response']
            });

            // 2. Post a status comment
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: '🔄 Waiting for your response.'
            });
